name: corn_disease_app
description: A Flutter web app for corn disease detection
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  file_picker: ^5.3.3  # Web-compatible
  image_picker: ^1.0.4
  permission_handler: ^10.4.4
  flutter:
    sdk: flutter
  # Google Sign-In
  google_sign_in: ^6.1.5
  # Firebase Core (required for all Firebase services)
  firebase_core: ^3.4.2
  # Firebase Auth
  firebase_auth: ^5.2.1
  # Optional: For better error handling
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/